apiVersion: v1
kind: Service
metadata:
  name: git
  namespace: git
  labels:
    app: gogs-app
spec:
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: gogs-app
  type: NodePort